# Generated by Django 6.1 on 2026-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('transfer', 'Transfer'), ('cut off', 'Cut Off')], default='Active', max_length=80),
            preserve_default=False,
        ),
    ]
