# Generated by Django 6.1 on 2026-09-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
