"""
Django settings for managemant_school project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from os import getenv 
from dotenv import load_dotenv 
from datetime import timedelta

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(getenv("DEBUG"))

ALLOWED_HOSTS = ["*"] #ini hanya untuk development


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'axes',
    'rest_framework',
    #'rest_framework_simplejwt',
    #'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'account',
    'student',
    'teacher',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.PageNumberPagination",

    "PAGE_SIZE": 20,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Management School API",
    "DESCRIPTION": (
        "Dokumentasi API otomatis (drf-spectacular) untuk sistem manajemen sekolah.<br><br>"
        "**Autentikasi:** session cookie. Login via `POST /auth/school/api/login/`, "
        "logout via `POST /auth/school/api/logout/` (memerlukan CSRF token dari `GET /auth/school/api/csrf/`).<br>"
        "`GET /auth/school/api/csrf/` adalah plain Django view (bukan DRF) sehingga tidak muncul di skema ini.<br><br>"
        "**Authorization:** endpoint student & teacher menggunakan `SchoolModelPermissions` — "
        "user yang login memerlukan permission Django sesuai method HTTP: "
        "`<app>.view_<model>` (GET/HEAD/OPTIONS), `<app>.add_<model>` (POST), "
        "`<app>.change_<model>` (PUT/PATCH), `<app>.delete_<model>` (DELETE)."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [
        {"name": "Auth", "description": "Register, login, logout, dan CSRF cookie."},
        {"name": "Student", "description": "CRUD data siswa (`Student`)."},
        {"name": "Student Profile", "description": "CRUD profil siswa (`StudentProfile`) — relasi one-to-one ke `Student`."},
        {"name": "Teacher", "description": "CRUD data guru (`Teacher`)."},
        {"name": "Teacher Profile", "description": "CRUD profil guru (`TeacherProfile`) — relasi one-to-one ke `Teacher`."},
    ],
    "ENUM_NAME_OVERRIDES": {
        "StudentStatusEnum": "student.models.student_model.Student.StatusChoice",
        "StudentGenderEnum": "student.models.student_model.Student.GenderChoice",
        "TeacherStatusEnum": "teacher.models.teacher_model.Teacher.StatusChoice",
    },
}

# Brute force protection (django-axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_LOCK_OUT_AT_FAILURE = True
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_RESET_ON_SUCCESS = True
AXES_HTTP_RESPONSE_CODE = 429



#ALLOWED_HOSTS = ["*"] # buat dev aja

# INI YANG KURANG
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "https://*.trycloudflare.com",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# WAJIB TAMBAHIN INI
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# PERBAIKI COOKIE NYA
SESSION_COOKIE_HTTPONLY = True  # tadinya False
CSRF_COOKIE_HTTPONLY = False 
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'managemant_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'managemant_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':getenv("db_name"),
        'USER':getenv("db_user"),
        'PASSWORD':getenv("db_pw"),
        'HOST':getenv("db_host"),
        'PORT':getenv("db_port"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
