# Generated by Django 6.1 on 2026-09-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=30, unique=True)),
                ('nis', models.CharField(max_length=10, unique=True)),
                ('nisn', models.CharField(max_length=16, unique=True)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transfer', 'Transfer'), ('drop out', 'Drop Out'), ('no have class', 'No Have Class')], max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=20)),
                ('addrees', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
    ]
