# Generated by Django 6.1 on 2026-09-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='addrees',
            new_name='address',
        ),
    ]
