# Generated by Django 6.1 on 2026-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_addrees_studentprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nis',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
