# Generated by Django 6.1 on 2026-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nis',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
